# Travis CI build file for KituraKit.

branches:
  only:
    - master
    - develop
    - /^issue.*$/

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR

sudo: required

jobs:
    include:
      - os: linux
        dist: trusty
        env: SWIFT_SNAPSHOT=4.0.3
      - os: linux
        dist: trusty
      - os: osx
        osx_image: xcode9.2
        env: SWIFT_SNAPSHOT=4.0.3
      - os: osx
        osx_image: xcode9.3
      - stage: Update
        script: ci/update.sh
        if: type = push AND branch = master
      - stage: Release
        script: ci/release.sh
        if: type = push AND branch = master
