# Travis CI build file for KituraKit.

branches:
  only:
    - master
    - develop
    - /^issue.*$/

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR

dist: trusty
sudo: required

jobs:
    include:
      - os: linux
        env: SWIFT_SNAPSHOT=4.0.3
      - os: linux
        env: SWIFT_SNAPSHOT=4.1.3
      - os: linux
      - os: linux
        env: DOCKER_IMAGE=ubuntu:16.04
      - os: linux
        env: DOCKER_IMAGE=ubuntu:16.04 SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT
      - os: linux
        env: DOCKER_IMAGE=ubuntu:18.04
      - os: osx
        osx_image: xcode9.2
        env: SWIFT_SNAPSHOT=4.0.3
      - os: osx
        osx_image: xcode9.4
        env: SWIFT_SNAPSHOT=4.1.2 JAZZY_ELIGIBLE=true
      - os: osx
        osx_image: xcode10
      - os: osx
        osx_image: xcode10.1
        env: SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT
      - stage: Update
        script: ci/update.sh
        if: type = push AND branch = master
      - stage: Release
        script: ci/release.sh
        if: type = push AND branch = master
