# Travis CI build file.

# whitelist (branches that should be built)
branches:
  only:
    - master
    - /^issue.*$/

dist: xenial
sudo: required

jobs:
    include:
      - os: linux
        services: docker
        env: DOCKER_IMAGE=swift:4.0.3 SWIFT_SNAPSHOT=4.0.3
      - os: linux
        services: docker
        env: DOCKER_IMAGE=swift:4.1.3 SWIFT_SNAPSHOT=4.1.3
      - os: linux
        services: docker
        env: DOCKER_IMAGE=swift:4.2.4 SWIFT_SNAPSHOT=4.2.4
      - os: linux
        services: docker
        env: DOCKER_IMAGE=swift:5.0.1-xenial
      - os: linux
        services: docker
        env: DOCKER_IMAGE=swift:5.0.1 SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT
      - os: osx
        osx_image: xcode9.2
        env: SWIFT_SNAPSHOT=4.0.3
      - os: osx
        osx_image: xcode9.4
        env: SWIFT_SNAPSHOT=4.1.2
      - os: osx
        osx_image: xcode10.1
        env: SWIFT_SNAPSHOT=4.2.1 JAZZY_ELIGIBLE=true
      - os: osx
        osx_image: xcode10.2
      - os: osx
        osx_image: xcode10.2
        env: SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
